version: "3.8"

services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=stationSki
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    image: bilelkort/devops:latest
    build: ./
    restart: always
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "123456",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "management.endpoints.web.exposure.include" : "*"
      }'
    stdin_open: true
    tty: true

volumes:
  db :