FROM openjdk:17-jdk-alpine

WORKDIR /app

# Update the name to match the one generated by Maven
COPY target/gestion-station-ski-1.1.jar /app/deops_project.jar

EXPOSE 8080

CMD ["java", "-jar", "deops_project.jar"]