global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['app:8089']  # Update this to the port your app exposes metrics on

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']


scrape_configs:
  - job_name: 'app'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['app:8089']
