#Server configuration
server.servlet.context-path=/api
server.port=8089
spring.mvc.format.date= yyyy-MM-dd
### DATABASE ###
spring.datasource.url=jdbc:mysql://192.168.33.10:3306/stationSki?createDatabaseIfNotExist=true
spring.datasource.username=docker_user
spring.datasource.password=Docker@1234!

### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect

### logging configuration ###
logging.level.root= info
# Logging pattern for the console
logging.pattern.console= =%d{yyyy-MM-dd HH:mm:ss} -  %-5level- %logger{45} - %msg %n


# Enable Prometheus metrics endpoint
management.endpoints.web.exposure.include=prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# Ensure the management endpoint is accessible on the same port
management.server.port=8089
management.server.address=0.0.0.0






